config/routes.rb
Rails.application.routes.draw do
  resources :consultations
  resources :hours
  resources :patients
  resources :medics
  devise_for :users
	root 'welcome#index'
	resource 'dashboard'
	

	authenticated :user do
		get 'dashboard/show' => 'dashboards#show'
		get 'my_hours' => 'dashboards#my_hours'
		get 'medic' => 'dashboards#medics'
		get 'med_hours' => 'dashboards#med_hours'
		get 'reserva' => 'dashboards#reserva'
		get 'getDays/:medic_id' => 'hours#days'
		get 'getHours/:day' => 'hours#hours'
		get 'patient_profile' => 'dashboards#patient_profile'
	end

	unauthenticated :user do
		devise_scope :user do
			get 'sessions/new' => 'sessions#new', as: :unregistered_root
		end
	end
	
	

end

app/models/hour.rb
# == Schema Information
#
# Table name: hours
#
#  id         :integer          not null, primary key
#  medic_id   :integer
#  day        :date
#  hour       :string
#  status     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_hours_on_medic_id  (medic_id)
#

class Hour < ActiveRecord::Base
  belongs_to :medic
  belongs_to :consultation

end

app/controllers/hours_controller.rb
class HoursController < ApplicationController
  before_action :set_hour, only: [:show, :edit, :update, :destroy]

  # GET /hours
  # GET /hours.json
  def index
    @hours = Hour.all
  end

  # GET /hours/1
  # GET /hours/1.json
  def show
  end

  # GET /hours/new
  def new
    @hour = Hour.new
    @times = create_hours(:start_time => 6.hours, :end_time => 20.hours)
  end

  # GET /hours/1/edit
  def edit
    @times = create_hours(:start_time => 6.hours, :end_time => 20.hours)
  end

  # POST /hours
  # POST /hours.json
  def create
    @days = params[:hour][:day].split(/\s*,\s*/)
    @hours = params[:hour][:hour]
    @days.each do |d|
      @hours.each do |h|
        if h.present?
          @hour = Hour.new(hour_params)
          @hour.day = d
          @hour.hour = h
          @hour.save
        end
      end
    end

    respond_to do |format|
      if @hour.save
        format.html { redirect_to '/dashboard', notice: 'Hora agregada.' }
        format.json { render :show, status: :created, location: @hour }
      else
        format.html { render :new }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end 
    
  end

  # PATCH/PUT /hours/1
  # PATCH/PUT /hours/1.json
  def update
    respond_to do |format|
      if @hour.update(hour_params)
        format.html { redirect_to @hour, notice: 'Hour was successfully updated.' }
        format.json { render :show, status: :ok, location: @hour }
      else
        format.html { render :edit }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hours/1
  # DELETE /hours/1.json
  def destroy
    @hour.destroy
    respond_to do |format|
      format.html { redirect_to hours_url, notice: 'Hour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def days 
    @days = Hour.where(medic_id: params[:medic_id])
    respond_to do |format|
      format.html
      format.json { render json: @days }
    end
  end

  def hours
    @hours = Hour.where(day: params[:day])
    respond_to do |format|
      format.html
      format.json { render json: @hours }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hour
      @hour = Hour.find(params[:id])
    end

    def create_hours(parameters)
      start_time = parameters[:start_time] ? parameters[:start_time] : 0
      end_time = parameters[:end_time] ? parameters[:end_time] : 24.hours
      increment = parameters[:increment] ? parameters[:increment] : 45.minutes
      Array.new(1 + (end_time - start_time)/increment) do |i|
          (Time.now.midnight + (i*increment) + start_time).strftime("%I:%M %p")
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hour_params
      params.require(:hour).permit(:medic_id, :day, :hour)
    end
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/views/hours/_form.html.erb
<%= form_for(@hour) do |f| %>
  <% if @hour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hour.errors.count, "error") %> prohibited this hour from being saved:</h2>

      <ul>
      <% @hour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :medic_id %><br>
    <%= f.text_field :medic_id %>
  </div>
  <div class="field">
    <%= f.label :day %><br>
    <%= f.date_select :day %>
  </div>
  <div class="field">
    <%= f.label :hour %><br>
    <%= f.select :hour, @times %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hours/edit.html.erb
<h1>Editing Hour</h1>

<%= render 'form' %>

<%= link_to 'Show', @hour %> |
<%= link_to 'Back', hours_path %>

app/views/hours/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hours</h1>

<table>
  <thead>
    <tr>
      <th>Medic</th>
      <th>Day</th>
      <th>Hour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hours.each do |hour| %>
      <tr>
        <td><%= hour.medic %></td>
        <td><%= hour.day %></td>
        <td><%= hour.hour %></td>
        <td><%= link_to 'Show', hour %></td>
        <td><%= link_to 'Edit', edit_hour_path(hour) %></td>
        <td><%= link_to 'Destroy', hour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hour', new_hour_path %>

app/views/hours/new.html.erb
<h1>New Hour</h1>

<%= render 'form' %>

<%= link_to 'Back', hours_path %>

app/views/hours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Medic:</strong>
  <%= @hour.medic %>
</p>

<p>
  <strong>Day:</strong>
  <%= @hour.day %>
</p>

<p>
  <strong>Hour:</strong>
  <%= @hour.hour %>
</p>

<%= link_to 'Edit', edit_hour_path(@hour) %> |
<%= link_to 'Back', hours_path %>