config/routes.rb
Rails.application.routes.draw do
  resources :consultations
  resources :hours
  resources :patients
  resources :medics
  devise_for :users
	root 'welcome#index'
	resource 'dashboard'
	

	authenticated :user do
		get 'dashboard/show' => 'dashboards#show'
		get 'my_hours' => 'dashboards#my_hours'
		get 'medic' => 'dashboards#medics'
		get 'med_hours' => 'dashboards#med_hours'
		get 'reserva' => 'dashboards#reserva'
		get 'getDays/:medic_id' => 'hours#days'
		get 'getHours/:day' => 'hours#hours'
		get 'patient_profile' => 'dashboards#patient_profile'
	end

	unauthenticated :user do
		devise_scope :user do
			get 'sessions/new' => 'sessions#new', as: :unregistered_root
		end
	end
	
	

end

app/models/medic.rb
# == Schema Information
#
# Table name: medics
#
#  id         :integer          not null, primary key
#  name       :string
#  speciality :string
#  dni        :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_medics_on_user_id  (user_id)
#

class Medic < ActiveRecord::Base
  belongs_to :user
  has_many :hours
  validates_presence_of :name, :dni, :speciality, :user
end

app/controllers/medics_controller.rb
class MedicsController < ApplicationController
  before_action :set_medic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /medics
  # GET /medics.json
  def index
    @medics = Medic.all
  end

  # GET /medics/1
  # GET /medics/1.json
  def show
  end

  # GET /medics/new
  def new
    @medic = Medic.new
  end

  # GET /medics/1/edit
  def edit
  end

  # POST /medics
  # POST /medics.json
  def create
    @medic = Medic.new(medic_params)
    @medic.user = current_user
    respond_to do |format|
      if @medic.save
        format.html { redirect_to @medic, notice: 'Medic was successfully created.' }
        format.json { render :show, status: :created, location: @medic }
      else
        format.html { render :new }
        format.json { render json: @medic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medics/1
  # PATCH/PUT /medics/1.json
  def update
    respond_to do |format|
      if @medic.update(medic_params)
        format.html { redirect_to @medic, notice: 'Medic was successfully updated.' }
        format.json { render :show, status: :ok, location: @medic }
      else
        format.html { render :edit }
        format.json { render json: @medic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medics/1
  # DELETE /medics/1.json
  def destroy
    @medic.destroy
    respond_to do |format|
      format.html { redirect_to medics_url, notice: 'Medic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medic
      @medic = Medic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medic_params
      params.require(:medic).permit(:name, :speciality, :dni, :user)
    end
end

app/helpers/medics_helper.rb
module MedicsHelper
end

app/views/medics/_form.html.erb
<%= form_for(@medic) do |f| %>
  <% if @medic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medic.errors.count, "error") %> prohibited this consultation from being saved:</h2>

      <ul>
      <% @medic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :speciality %><br>
    <%= f.text_field :speciality %>
  </div>
  <div class="field">
    <%= f.label :dni %><br>
    <%= f.text_field :dni %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medics/edit.html.haml
%h1 Editing medic

= render 'form'

= link_to 'Show', @medic
\|
= link_to 'Back', medics_path

app/views/medics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Medics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Speciality</th>
      <th>Dni</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medics.each do |medic| %>
      <tr>
        <td><%= medic.name %></td>
        <td><%= medic.speciality %></td>
        <td><%= medic.dni %></td>
        <td><%= medic.user %></td>
        <td><%= link_to 'Show', medic %></td>
        <td><%= link_to 'Edit', edit_medic_path(medic) %></td>
        <td><%= link_to 'Destroy', medic, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medic', new_medic_path %>

app/views/medics/new.html.erb
<h1>New medic</h1>

<%= render 'form' %>

<%= link_to 'Back', medics_path %>

app/views/medics/show.html.erb
%p#notice= notice

%p
  %b Name:
  = @medic.name
%p
  %b Speciality:
  = @medic.speciality
%p
  %b Dni:
  = @medic.dni
%p
  %b User:
  = @medic.user

= link_to 'Edit', edit_medic_path(@medic)
\|
= link_to 'Back', medics_path