config/routes.rb
Rails.application.routes.draw do
  resources :consultations
  resources :hours
  resources :patients
  resources :medics
  devise_for :users
	root 'welcome#index'
	resource 'dashboard'
	

	authenticated :user do
		get 'dashboard/show' => 'dashboards#show'
		get 'my_hours' => 'dashboards#my_hours'
		get 'medic' => 'dashboards#medics'
		get 'med_hours' => 'dashboards#med_hours'
		get 'reserva' => 'dashboards#reserva'
		get 'getDays/:medic_id' => 'hours#days'
		get 'getHours/:day' => 'hours#hours'
		get 'patient_profile' => 'dashboards#patient_profile'
	end

	unauthenticated :user do
		devise_scope :user do
			get 'sessions/new' => 'sessions#new', as: :unregistered_root
		end
	end
	
	

end

app/models/consultation.rb
# == Schema Information
#
# Table name: consultations
#
#  id         :integer          not null, primary key
#  patient_id :integer
#  hour_id    :integer
#  status     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_consultations_on_hour_id     (hour_id)
#  index_consultations_on_patient_id  (patient_id)
#

class Consultation < ActiveRecord::Base
  belongs_to :patient
  belongs_to :hour
end

app/controllers/consultations_controller.rb
class ConsultationsController < ApplicationController
  before_action :set_consultation, only: [:show, :edit, :update, :destroy]

  # GET /consultations
  # GET /consultations.json
  def index
    @consultations = Consultation.all
  end

  # GET /consultations/1
  # GET /consultations/1.json
  def show
  end

  # GET /consultations/new
  def new
    @consultation = Consultation.new
  end

  # GET /consultations/1/edit
  def edit
  end

  # POST /consultations
  # POST /consultations.json
  def create
    if consultation_params[:hour_id].present?
      @consultation = Consultation.new(consultation_params)
      if @consultation.save 
          Hour.update(consultation_params[:hour_id], :status => "tomada")
          redirect_to '/dashboard', notice: 'Hora reservada'
        else
          redirect_to '/reserva', flash: {consultation_error: "No se puedo reservar la hora"}
      end
    else
        redirect_to '/reserva', flash: {consultation_error: "Debes seleccionar una hora"}
    end
  end

  # PATCH/PUT /consultations/1
  # PATCH/PUT /consultations/1.json
  def update
    respond_to do |format|
      if @consultation.update(consultation_params)
        format.html { redirect_to @consultation, notice: 'Consultation was successfully updated.' }
        format.json { render :show, status: :ok, location: @consultation }
      else
        format.html { render :edit }
        format.json { render json: @consultation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultations/1
  # DELETE /consultations/1.json
  def destroy
    @consultation.destroy
    respond_to do |format|
      format.html { redirect_to consultations_url, notice: 'Consultation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultation
      @consultation = Consultation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consultation_params
      params.require(:consultation).permit(:patient_id, :hour_id, :status)
    end
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/views/consultations/_form.html.erb
<%= form_for(@consultation) do |f| %>
  <% if @consultation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consultation.errors.count, "error") %> prohibited this consultation from being saved:</h2>

      <ul>
      <% @consultation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.text_field :patient_id %>
  </div>
  <div class="field">
    <%= f.label :hour_id %><br>
    <%= f.text_field :hour_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/consultations/create.html.erb
<h2>Form Data - display</h2>



<hr>
<%= debug(params) %>

app/views/consultations/edit.html.erb
<h1>Editing Consultation</h1>

<%= render 'form' %>

<%= link_to 'Show', @consultation %> |
<%= link_to 'Back', consultations_path %>

app/views/consultations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Consultations</h1>

<table>
  <thead>
    <tr>
      <th>Patient</th>
      <th>Hour</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @consultations.each do |consultation| %>
      <tr>
        <td><%= consultation.patient %></td>
        <td><%= consultation.hour %></td>
        <td><%= consultation.status %></td>
        <td><%= link_to 'Show', consultation %></td>
        <td><%= link_to 'Edit', edit_consultation_path(consultation) %></td>
        <td><%= link_to 'Destroy', consultation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Consultation', new_consultation_path %>

app/views/consultations/new.html.erb
<h1>New Consultation</h1>

<%= render 'form' %>

<%= link_to 'Back', consultations_path %>

app/views/consultations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient:</strong>
  <%= @consultation.patient %>
</p>

<p>
  <strong>Hour:</strong>
  <%= @consultation.hour %>
</p>

<p>
  <strong>Status:</strong>
  <%= @consultation.status %>
</p>

<%= link_to 'Edit', edit_consultation_path(@consultation) %> |
<%= link_to 'Back', consultations_path %>